[package]
name = "libfuzzer-sys"
version = "0.1.0"
authors = ["Simonas Kazlauskas <git@kazlauskas.me>"]
repository = "https://github.com/rust-fuzz/libfuzzer-sys"

# cargo-fuzz puts this in a crate subdirectory,
# which causes problems if the crate uses workspaces.
# Create a useless local workspace to break out of this
[workspace]
members = ["."]

[dependencies]

[build-dependencies]
gcc = "0.3"
